# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 (1..3).each do |i|
   config.vm.define "lab#{i}" do |node|
    node.vm.box = "centos-7.4-base"
    
    node.ssh.insert_key = false
    node.vm.hostname = "lab#{i}"
    
    node.vm.network "private_network", ip: "11.11.11.11#{i}"
    
    node.vm.provision "shell", run: "always",
      inline: "ntpdate ntp.api.bz"
      
    node.vm.provision "shell", run: "always",
      inline: "echo hello from lab#{i}"
    
    node.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.customize ["modifyvm", :id, "--name", "lab#{i}", "--memory", "2048"]
    end
   end
 end
end