apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis
spec:
  hosts:
  - redis
  tcp:
  - match:
    - port: 6379
    route:
    - destination:
        host: redis
        port:
          number: 6379